### ISSUE TITLE
🐞 - incorrect erasing selection with `decimalSeparator` in `Number`

### ISSUE THREAD

**Issue by KrollikRoddzer** [taiga-family/maskito#1192]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://maskito.dev/kit/number/API?precision=5&decimalZeroPadding=true

### Description

`DecimalZeroPadding` = **true**
`Precision` = **5**

Type: `134.00300` => select `13|4.003|00` => deleteBackward(Forward) => `13.00000`
But was `1 300.00000`

### Maskito version

2.2.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
We've discussed this issue with @KrollikRoddzer.

And our final solution – do not fix it for a while.
Reason is simple – this issue is rather controversial and can interpreted differently by different people.

Let's explore this case:
```
12|3,4|5 => Backspace => 12,5
12|3,4|5 => Backspace => 125
```

Both cases can be valid. 
At the present time Maskito works in the first way.
Let's keep it untouched.
