### ISSUE TITLE
🐞 - Issue with date parsing from datetime string

### ISSUE THREAD

**Issue by movedoa** [taiga-family/maskito#1501]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://stackblitz.com/edit/mb1gju?file=index.ts

### Description

```
maskitoTransform(
    '2024-08-27T16:04:20.871',
    maskitoDateTimeOptionsGenerator({
      dateMode: 'dd/mm/yyyy',
      timeMode: 'HH:MM',
      dateSeparator: '.',
      dateTimeSeparator: ' ',
    })
  )
```
  
Expeced output:
`27.08.2024 16:04`
  
Actual output:
`20.02.0827 16:04`

Same issue happens with just date options:
```
maskitoTransform(
   '2024-08-27T16:04:20.871',
   maskitoDateOptionsGenerator
   ({mode: 'dd/mm/yyyy', separator: '.'}))
```

Expeced output:
`27.08.2024`
  
Actual output:
`20.02.0827`

### Maskito version

3.0.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@movedoa Hello!

[maskitoTransform](https://maskito.dev/core-concepts/transformer) utility is **not** about parsing of any value (we don't have plans to reinvent `date-fns` library inside Maskito). It is about formatting of value (and calibrating with fixed characters) with already known format.
Use `Intl.DateTimeFormat` (or any other existing libraries for parsing date string) to parse value before passing it inside `maskitoTransform`:

```ts
const dateFormatOptions: Intl.DateTimeFormatOptions = {
  year: 'numeric',
  month: 'numeric',
  day: 'numeric',
  hour: 'numeric',
  minute: 'numeric',
};
const date = new Date('2024-08-27T16:04:20.871');
const dateString = new Intl.DateTimeFormat('en-GB', dateFormatOptions).format(date);

const maskitoOptions = maskitoDateTimeOptionsGenerator({
  dateMode: 'dd/mm/yyyy',
  timeMode: 'HH:MM',
  dateSeparator: '.',
  dateTimeSeparator: ' ',
});

maskitoTransform(dateString, maskitoOptions); // 27.08.2024 16:04
```

Learn more:
https://stackblitz.com/edit/maskito-intl-date-time-format

**Comment by b-mi** [comment]
It's not about inventing new date-fns. The problem is not the transfer itself. The problem is the integration of that transfer into this library. Unfortunately, the processors do not solve this problem as I originally assumed. They solve something that I don't really need. The fact that such a complex library does not support events for the transformation of the iso value to the user value and vice versa is the reason why not to use this library. The example in stackblitz is nice, but in the real application there are dozens of those date inputs.
