### ISSUE TITLE
How to create strict date and time input?

### ISSUE THREAD

**Issue by movedoa** [taiga-family/maskito#1520]
### Which package(s) are the source of the bug?

@maskito/kit

### Playground Link

https://maskito.dev/kit/date#min-max

### Description

I'm trying to create a date input field and a time input field that can not be empty and always has a valid date or time.
I found #1217 which states:

> This behavior is already implemented in our mask.
> In strict mode, if a user tries to enter a non-valid date, the mask will either prevent the user from entering such a date, or if it is possible to turn it into a valid date, it will change it to a valid date. Textfield's value NEVER contains invalid date value.

If this behavious is already implemented, how do i activate this?
Even with min & max set, i can still just input any number into the date field, for example just a 1.

![grafik](https://github.com/user-attachments/assets/b2c138e7-7fef-4613-8ae3-186c5c5cf7fd)

If this is not possible by default, is there an easy way to abort a user input in a pre or postprocessor?

### Maskito version

3.0.1

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
The mask will turn the fully entered date into a valid date, meaning if you entered a date earlier than min — it would be converted or if you entered 13th month etc. But it will not disallow you typing intermediary states. For your situation, maybe a good idea would be to add a plugin that sets the value on blur?

**Comment by movedoa** [comment]
I dont want to allow any intermediary state at any time, i start with a valid date and i just want to cancel every user input that would lead to an invalid date. Same with time.

**Comment by raegen** [comment]
@movedoa it cannot be done even with plain integers, much less for dates. To be specific, it can be implement done for `max`, but it cannot be done for `min` and the reason is of a logical nature. Funerals start with fun (pun intended). 
To enable typing in some string value `xxx`, each intermediate state (`state.substring(0, n) where n = 1, state.length`) must be allowed as well. For "Funerals", that amounts to ['F', 'Fu', 'Fun', 'Fune', 'Funer', 'Funera', 'Funeral']. Furthermore, when it comes to integers, the intermediate states are not linear, since:
1. Length is not the only variable anymore, now we have content that produces n permutations that satisfy the given constraint
2. And even the above is only the case if there's a maximum as well. If there's no maximum, any valid integer is a valid intermediate state, since regardless of what it is, appending enough or more than enough (up to infinity) digits will make it satisfy `min`. 

> ❌ 1 > 900
> ❌ 10 > 900
> ❌ 100 > 900
> ✔️ 1000 > 900

**Comment by waterplea** [comment]
Technically you can do it the way you want, it's just going to be frustration simulator for your users. Imagine they want to type in 31 of January while the input contains 28 of February. You would force them to go change the month first then go and change the date and no other way to do it. It's much easier to just erase the whole value and type in 31.02 — especially on the phone with numbers keyboard, than to try and move caret around an undeletable string value to edit the parts in the only order that works.
