### ISSUE TITLE
🚀 - Options to get Raw/Original/Unmask value

### ISSUE THREAD

**Issue by hihahihahoho** [taiga-family/maskito#560]
### Description

for example if i input number: 100000, i will be able to get { value: 100,000,  rawValue: 100000}

**Comment by waterplea** [comment]
That would not be possible for any complex masking case, because original value can be changed tremendously. You get raw values in processors, but after everything is finished — it's gone. Say your postprocessor changes all 'good' into 'bad'. Then you go and add a char in the middle to make it 'bard'. What would be the raw value? If you just want to have the unformated number, there's a utility function `maskitoParseNumber` mentioned in the docs at the very top:
https://maskito.dev/kit/number

**Comment by igoraugustynski** [comment]
I actually think this would be pretty useful - in some cases I need to format a postal code for user input with a separator, like "12-345" but the API I'm sending this value to expects a clean value, without the "12345". I understand that removing the mask after it is applied is impossible, but it seems feasible to just keep the unformatted value somewhere else.

**Comment by waterplea** [comment]
I gave an example where there is no such thing as "unformatted" value generally speaking. You have a few options:

1) unmask your values before sending them to the API.
2) make a plugin to emit raw value for every input — listen to `beforeinput` event in `capture` phase to make sure it kicks in before masking
3) create a wrapper for storing your values that would mask and unmask automatically.

Here's an example using Angular:
https://stackblitz.com/edit/angular-4hcxec?file=src%2Fapp%2Funmask.directive.ts

**Comment by pablomaurer** [comment]
Update @waterplea Versions 3: The directive version in case anyone interesed:

**The Directive**
````ts
import { Directive, effect, input, OnInit } from '@angular/core';
import type { MaskitoOptions } from '@maskito/core';
import { MaskitoDirective } from '@maskito/angular';
import { DefaultValueAccessor } from '@angular/forms';

export type UnmaskFn = (value: unknown) => unknown;
export interface MaskOptions {
  maskitoOptions: MaskitoOptions;
  unmaskFn?: UnmaskFn;
}

@Directive({
  selector: '[ingMask]',
  standalone: true,
  hostDirectives: [
    {
      directive: MaskitoDirective,
      inputs: ['maskitoElement'],
    },
  ],
})
export class MaskDirective implements OnInit {
  options = input.required<MaskOptions>({ alias: 'ingMask' });

  constructor(
    private maskito: MaskitoDirective,
    private accessor: DefaultValueAccessor,
  ) {
    effect(() => {
      this.maskito.options = this.options().maskitoOptions;
      void this.maskito.ngOnChanges();
    });
  }

  ngOnInit() {
    const unmaskFn = this.options().unmaskFn;

    if (unmaskFn) {
      const original = this.accessor.onChange.bind(this);
      this.accessor.onChange = (value) => original(unmaskFn(value));
    }
  }
}
````
**Usage in TS**
````ts
  protected readonly control = new FormControl<any>('');
  protected readonly maskitoOptions: MaskOptions = {
    maskitoOptions: { mask: [/\d/, /\d/, ':', /\d/, /\d/] },
    unmaskFn: (value) => {
      return (value as string).substring(0, 2);
    },
  };
````

**Usage in HTML**
````html
<input [formControl]="control" [ingMask]="maskitoOptions" />
<button (click)="setValue()">Set 1231</button>
<div>value: {{ control.getRawValue() }}</div>
````

**Comment by ggomarighetti** [comment]
I don't want to play devil's advocate here, but it would be good to develop a solution, especially considering that the library has recently added new features that are already available, and that there is a requirement for this case (otherwise there would be no implementations by users).

Something similar to what imask implements (to name one) in which one can pass a pattern similar to a regex and identify characters that are not fixed, in order to eliminate them in something similar to a reconversion.

**Comment by waterplea** [comment]
@ggomarighetti I already explained that it is technically impossible to to in a general way and Maskito is general masking solution. It gives you total freedom and that limits it in a sense, because it is simply impossible to have unmasked/raw value in that case. You can read my comments above for the reasoning. All potential solutions, including the one you suggest, are just concrete bandaids for concrete situations, not general solutions.

- For numbers there's `maskitoParseNumber`/`maskitoStringifyNumber`
- For dates there's `maskitoParseDate` /`maskitoStringifyDate`
- For time there's `maskitoParseTime`/`maskitoStringifyTime`
- For datetime there's `maskitoParseDateTime`/`maskitoStringifyDateTime`

And there's nothing we can do for arbitrary masking, besides give advice on how to approach it, which I did above. Even if we were to make the unmask handler an official solution - there's no way to make it framework agnostic since all frameworks have their own approach to forms and we want to be very cautious inventing our own APIs/conventions like storing unmasked values in some data-attributes on input tag.

**Comment by ggomarighetti** [comment]
Hello @waterplea ,

I read the comments, and I understand the point about not being able to access a raw value, but I think an unmasked value could be achieved.

That is, it would be something like a parameterization, where different characters to be ignored are accepted in a new method, something like the inverse of maskitoTransform, similar to how one can specify which separator they want in the Date Kit or which keys they want to be mapped as decimal separators in the Number Kit.

I understand that maskito gives total freedom in this, and that it would be the equivalent of putting together a post-processor, having an array stored with the characters and doing a replace, but my idea was to propose it and have it exist in the library as such.

I know this doesn't convince you, just as in previous issues I talked about an overlap between thousandSeparators and decimalSeparators in Latin American keyboard layouts.

But both things are solved (and I solved them) with post-processors, but they get stuck in an issue on GitHub.

They are not integrated into the documentation or anything like that anywhere. At least update the documentation page and be able to suggest/post/etc. post-processors that perform these functions that more than one person mentions in some issues, make access as easy and simple as possible, copy a snippet and that's it. If you don't think it's an official solution, at least use it as an example.

What's more, following this whole copy-paste trend, it would be great to create an llms.txt file to ensure that the library is offered as an option in the different models and that they have all these tools at their fingertips.
