### ISSUE TITLE
🐞 - maskitoPhoneOptionsGenerator allows to enter invalid Ukrainian phone number

### ISSUE THREAD

**Issue by davidarny** [taiga-family/maskito#714]
### Which package(s) are the source of the bug?

@maskito/core, @maskito/kit, @maskito/react

### Playground Link

https://stackblitz.com/edit/stackblitz-starters-1aetx2

### Description

Hi!
Very much appreciated for this library! Love it ❤️

I'm using a function `maskitoPhoneOptionsGenerator` from `@masktio/phone` and having some issues with masking against Ukrainian phone numbers.

A valid Ukrainian phone number includes 9 digits after `+380` country code. I'm validating phone number with `libphonenumber-js` and getting invalid results when user types 10 digits. Question is why user is able to type 10 digits?

![Screen Recording 2023-12-04 at 23 07 38 mov](https://github.com/taiga-family/maskito/assets/17799810/160df27c-c3b5-479b-bae5-27ed2f9f544b)

### Maskito version

1.9.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by waterplea** [comment]
`libphonenumber` has several reasons for the number to be invalid. One particular one is "TOO LONG". I believe we only limit length of the number once it hits this error since we delegate source of truth to `libphonenumber` because we cannot know about every country phone number lengths:
https://github.com/taiga-family/maskito/blob/main/projects/phone/src/lib/masks/phone/utils/cut-phone-by-valid-length.ts
Some countries my have valid phones of different lengths.
